#pragma once

#include <game/bases/d_base_actor.hpp>
#include <game/bases/d_heap_allocator.hpp>
#include <game/mLib/m_3d/mdl.hpp>
#include <game/mLib/m_3d/anm_chr.hpp>
#include <game/mLib/m_3d/anm_tex_pat.hpp>

/// @brief The actor for a collectible power-up item found on the World Map
/// (mushroom, fire flower, propeller mushroom, ice flower, penguin suit,
/// star).
/// @unofficial Class name and most member names are guesses -- see
/// wip/wm_units/agent_item/MAPPING.md. Layout below is measured directly:
/// every offset was cross-checked against the target ctor's explicit
/// field-zeroing stores (fn_2_167150) with a STATIC_ASSERT/Probe compile,
/// and sizeof(daWmItem_c) == 0x210 matches the target's
/// `li r3,0x210; bl __nw__7fBase_cFUl` exactly.
/// @ingroup bases
class daWmItem_c : public dBaseActor_c {
public:
    daWmItem_c();
    ~daWmItem_c();

    /// @unofficial fn_2_167120 is generated by the ACTOR_PROFILE macro
    /// (`void *classInit() { return new daWmItem_c(); }`) -- not declared
    /// here, matching source/d_basesNP/bases/d_a_wm_kinoko_base.cpp's
    /// precedent.

    virtual int doDelete(); ///< @unofficial fn_2_1674A0, trivial `return 1;`

    /// @unofficial fn_2_1672A0. Must be `virtual int create()` -- mwcc
    /// rejects a `void create()` override of `fBase_c::create()` (error
    /// 10227). The target itself never sets r3 before returning, which is
    /// still open (see MAPPING.md); returning SUCCEEDED here is a guess.
    virtual int create();

    void createModel();     ///< @unofficial fn_2_1674B0, largest function (0x298)
    void calcModel();       ///< @unofficial fn_2_1677D0
    void cycleAnm();        ///< @unofficial fn_2_167750, advances the mAnmChr animation index

    /// @unofficial fn_2_167350/1673C0/167430. Like create(), never called
    /// from within this unit -- likely reached through the "secondary
    /// vtable" mechanism at `this+0x60` (dBase_c-derived classes get this
    /// pointer set automatically; see MAPPING.md), so their exact
    /// interface/virtual-ness is unconfirmed.
    bool step0();  ///< @unofficial always `return true;` -- target sets r3=1 unconditionally before returning
    void step1();
    void step2();

    dHeapAllocator_c mAllocator;       ///< @0x128
    m3d::mdl_c mModel;                 ///< @0x144
    m3d::anmChr_c mAnmChr;             ///< @0x184, measured sizeof 0x38
    nw4r::g3d::ResFile mResFile;       ///< @0x1bc, main model archive (from getRes(itemName, "g3d/<itemName>.brres"))
    nw4r::g3d::ResFile mAnimResFile;   ///< @0x1c0, animation archive (from getRes(SI_name, "g3d/model.brres"))
    nw4r::g3d::ResAnmTexPat mResAnmTexPat; ///< @0x1c4, held only transiently by createModel()
    m3d::anmTexPat_c mAnmTexPat;      ///< @0x1c8, measured sizeof 0x2c; its mpChildren (last word, @0x1f0) is
                                       ///< the ctor's `stw r31, 0x1f0(r29)` -- not a separate field
    float mMotion[3];                 ///< @0x1f4, set by create()/calcModel() from lbl_2_rodata_8988
    int m_200;                        ///< @0x200, set to 2 by create(). Signed -- target uses `cmpw`, not `cmplw`.
    int m_204;                        ///< @0x204, set to 2 by create()
    u8 m_208;                         ///< @0x208, zeroed by ctor, set to 1 by create()
    u8 m_209;                         ///< @0x209
    u8 m_20a;                         ///< @0x20a
    u8 m_20b;                         ///< @0x20b
    int mItemType;                     ///< @0x20c, mParam & 0xF -- item type selector (0=kinoko .. 6=star, 5 reuses
                                       ///< kinoko's archive). Signed, not u32 -- the target compares it with
                                       ///< `cmpwi` (signed), not `cmplwi`.
};
