import os, sys

fndiff_all_path = 'scratch/gemini_round24/fndiff_all_fresh.txt'
with open(fndiff_all_path, 'r', encoding='utf-8') as fh:
    fndiff_all_raw = fh.read().strip()

ticks = '```'

s = []
s.append('# Round 30 Report: `d_enemy_toride_kokoopa` Baseline Re-Verification, `setQuakeDead` Variant Analysis, & Promotion Manifest\n\n')

s.append('## 1. Summary & Headline Metrics\n\n')
s.append('- **Current Standing (Round 30)**:\n')
s.append('  - Total Functions in TU: **251** (31,876 bytes)\n')
s.append('  - Matched Functions: **248 / 251 (98.80%)**\n')
s.append('  - Matched Bytes: **30,816 / 31,876 bytes (96.67%)**\n')
s.append('  - Disagreements vs 248 / 251: **None** (confirmed independently by `fndiff.py --all` and `tool.py` under the union gate / naming-artifact rule).\n')
s.append('  - Unmatched Functions: **3 / 251 (1,060 bytes total)**\n')
s.append('    - `setQuakeDead__18dEnTorideKokoopa_cFv` (340 B / 85 words target vs 88 words draft)\n')
s.append('    - `initializeState_Jump__18dEnTorideKokoopa_cFv` (360 B / bounded negative)\n')
s.append('    - `initializeState_BigJump__18dEnTorideKokoopa_cFv` (360 B / bounded negative)\n')
s.append('- **GAINED Functions**: **0**\n')
s.append('- **LOST Functions**: **0** (Zero regressions across all 248 matching functions).\n')
s.append('- **Constant Pool Verification (`poolcheck.py`)**:\n')
s.append('  - `177 pooled constants compared by VALUE across 250 paired functions`\n')
s.append('  - `0 mismatched, 0 could not be resolved on one side` (Exit code: 0 clean).\n\n')

s.append('---\n\n')

s.append('## 2. GAINED & LOST Sections\n\n')
s.append('### GAINED Functions (0 Gained)\n')
s.append('No new functions reached 100% byte-identity in Round 30.\n\n')

s.append('### LOST Functions (0 Lost)\n')
s.append('Zero functions regressed or left the matched set in Round 30.\n\n')

s.append('### Explicit Artifact-Matched Pair Re-Check:\n')
s.append('1. **`__sinit_\d_enemy_toride_kokoopa_cpp` (5,784 B / 1,446 insns / frame `0x420`):**\n')
s.append('   - Raw Byte Diffs: **0** (1,446 / 1,446 instructions byte-identical)\n')
s.append('   - Canonical Diffs in `fndiff.py`: **0** (+ 4 naming artifacts: `...data.0`, `...bss.0`, and dtk symbol address disambiguation suffixes)\n')
s.append('   - Status: **MATCHED 100%** (under union gate / naming-artifact rule)\n')
s.append('2. **`executeState_ShellAtk_St__18dEnTorideKokoopa_cFv` (612 B / 153 insns / frame `0x10`):**\n')
s.append('   - Raw Byte Diffs: **0** (153 / 153 instructions byte-identical)\n')
s.append('   - Canonical Diffs in `fndiff.py`: **0** (+ 6 naming artifacts: `...bss.0`, `lbl_802F0C80` vs `l_bounceSpeed`)\n')
s.append('   - Status: **MATCHED 100%** (under union gate / naming-artifact rule)\n')
s.append('3. **`executeState_LandOn__18dEnTorideKokoopa_cFv` (236 B / 59 insns / frame `0x10`):**\n')
s.append('   - Raw Byte Diffs: **0** (59 / 59 instructions byte-identical)\n')
s.append('   - Canonical Diffs in `fndiff.py`: **0** (+ 3 naming artifacts)\n')
s.append('   - Status: **MATCHED 100%**\n')
s.append('4. **`initializeState_ShellAtk_St__18dEnTorideKokoopa_cFv` (508 B / 127 insns / frame `0x20`):**\n')
s.append('   - Raw Byte Diffs: **0** (127 / 127 instructions byte-identical)\n')
s.append('   - Canonical Diffs in `fndiff.py`: **0** (+ 12 naming artifacts)\n')
s.append('   - Status: **MATCHED 100%**\n\n')

s.append('---\n\n')

s.append('## 3. Work Order Item 1: `setQuakeDead` Variant Sweep & Canonical Analysis\n\n')
s.append('### 3.1. Target Function Profile\n')
s.append('- **Symbol**: `setQuakeDead__18dEnTorideKokoopa_cFv` (`0x800A9A90`, size 340 B)\n')
s.append('- **Target Metrics**: 85 words / frame `0x30` / GPR saves `[30, 31]` / FPR saves `none`\n')
s.append('- **Target Control-Flow Shape**:\n')
s.append('```asm\n')
s.append('800A9AF0: li    r0, 0x0\n')
s.append('800A9AF4: sth   r0, 0x792(r30)                     ; mUnk792 = 0\n')
s.append('800A9AF8: lfs   f1, "@75100"@sda21(r0)            ; 0.0f\n')
s.append('800A9AFC: mr    r4, r30                            ; this\n')
s.append('800A9B00: sth   r0, 0x790(r30)                     ; mUnk790 = 0\n')
s.append('800A9B04: li    r5, 0x6\n')
s.append('800A9B08: lfs   f2, "@75250"@sda21(r0)            ; 24.0f\n')
s.append('800A9B0C: lwz   r3, m_instance__11dScoreMng_c@sda21(r0)\n')
s.append('800A9B10: bl    UnKnownScoreSet__11dScoreMng_cFP8dActor_cUlff\n')
s.append('800A9B14: lwz   r3, 0x770(r30)                     ; load mUnk770\n')
s.append('800A9B18: cmpwi r3, 0x0\n')
s.append('800A9B1C: bne   .L_call\n')
s.append('800A9B20: li    r3, 0x0                            ; <-- NULL materialised in r3\n')
s.append('800A9B24: b     .L_check                           ; <-- branched into shared compare\n')
s.append('.L_call:\n')
s.append('800A9B28: bl    searchBaseByID__10fManager_cF9fBaseID_e\n')
s.append('.L_check:\n')
s.append('800A9B2C: cmpwi r3, 0x0                            ; <-- single shared test on merged value\n')
s.append('800A9B30: beq   .L_skip\n')
s.append('800A9B34: bl    deleteRequest__7fBase_cFv\n')
s.append('.L_skip:\n')
s.append('```\n\n')

s.append('### 3.2. Measured Variants Comparison Table\n\n')
s.append('| Variant | Source Code Shape | Ternary Shape (`li r3,0` + `b` -> shared `cmpwi`) | Words | Frame | Non-Volatile Set (GPR) | `fndiff.py` Diffs |\n')
s.append('| :--- | :--- | :---: | :---: | :---: | :---: | :---: |\n')
s.append('| **Variant A (Baseline Semantic Ternary)** | `fBase_c *base = (mUnk770 == 0) ? nullptr : fManager_c::searchBaseByID((fBaseID_e)mUnk770); if (base != nullptr) base->deleteRequest();` | NO (hoists `r29`) | 88 | `0x40` | `[29, 30, 31]` | **83** (80 insn diffs + 3 length diff) |\n')
s.append('| **Variant 1 (Explicit `(fBase_c*)0` Pointer Cast)** | `fBase_c *base = (mUnk770 == 0) ? (fBase_c*)0 : fManager_c::searchBaseByID((fBaseID_e)mUnk770); if (base != 0) base->deleteRequest();` | NO (hoists `r29`) | 88 | `0x40` | `[29, 30, 31]` | **83** (80 insn diffs + 3 length diff) |\n')
s.append('| **Variant 2 (Explicit `(fBase_c*)NULL` Cast)** | `fBase_c *base = (mUnk770 == 0) ? (fBase_c*)NULL : fManager_c::searchBaseByID((fBaseID_e)mUnk770); if (base != NULL) base->deleteRequest();` | NO (hoists `r29`) | 88 | `0x40` | `[29, 30, 31]` | **83** (80 insn diffs + 3 length diff) |\n')
s.append('| **Variant 3 (Inverted Ternary `!= 0`)** | `fBase_c *base = (mUnk770 != 0) ? fManager_c::searchBaseByID((fBaseID_e)mUnk770) : (fBase_c*)0; if (base != 0) base->deleteRequest();` | NO (hoists `r29`) | 87 | `0x40` | `[29, 30, 31]` | **84** (82 insn diffs + 2 length diff) |\n')
s.append('| **Variant 4 (`if/else` Local Assignment `0 / call`)** | `fBase_c *base; if (mUnk770 == 0) base = (fBase_c*)0; else base = fManager_c::searchBaseByID((fBaseID_e)mUnk770); if (base != 0) base->deleteRequest();` | NO (hoists `r29`) | 88 | `0x40` | `[29, 30, 31]` | **83** (80 insn diffs + 3 length diff) |\n')
s.append('| **Variant 5 (`if/else` Local Assignment `call / 0`)** | `fBase_c *base; if (mUnk770 != 0) base = fManager_c::searchBaseByID((fBaseID_e)mUnk770); else base = (fBase_c*)0; if (base != 0) base->deleteRequest();` | NO (hoists `r29`) | 87 | `0x40` | `[29, 30, 31]` | **84** (82 insn diffs + 2 length diff) |\n')
s.append('| **Variant 6 (Typed Zero Stores `(s16)0`)** | `mUnk792 = (s16)0; mUnk790 = (s16)0;` with ternary | NO (hoists `r29`) | 88 | `0x40` | `[29, 30, 31]` | **83** (80 insn diffs + 3 length diff) |\n')
s.append('| **Variant 7 (Typed Zero Stores `(u16)0`)** | `mUnk792 = (u16)0; mUnk790 = (u16)0;` with ternary | NO (hoists `r29`) | 88 | `0x40` | `[29, 30, 31]` | **83** (80 insn diffs + 3 length diff) |\n')
s.append('| **Variant 8 (`dActor_c*` Cast as in `setQuakeDamage`)** | `dActor_c *act = (mUnk770 == 0) ? nullptr : (dActor_c*)fManager_c::searchBaseByID((fBaseID_e)mUnk770); if (act != nullptr) act->deleteRequest();` | NO (hoists `r29`) | 88 | `0x40` | `[29, 30, 31]` | **83** (80 insn diffs + 3 length diff) |\n')
s.append('| **Variant 9 (`fBaseID_e` Enum 0 Cast in Ternary)** | `fBase_c *base = ((fBaseID_e)mUnk770 == (fBaseID_e)0) ? (fBase_c*)0 : fManager_c::searchBaseByID((fBaseID_e)mUnk770); if (base) base->deleteRequest();` | NO (hoists `r29`) | 88 | `0x40` | `[29, 30, 31]` | **83** (80 insn diffs + 3 length diff) |\n')
s.append('| **Variant 10 (Ternary Inside Condition)** | `if (fBase_c *base = (mUnk770 == 0 ? (fBase_c*)0 : fManager_c::searchBaseByID((fBaseID_e)mUnk770))) base->deleteRequest();` | NO (hoists `r29`) | 88 | `0x40` | `[29, 30, 31]` | **83** (80 insn diffs + 3 length diff) |\n')
s.append('| **Variant 11 (Chain Assignment `mUnk792 = mUnk790 = 0`)** | `mUnk792 = mUnk790 = 0;` with ternary | NO (hoists `r29`) | 88 | `0x40` | `[29, 30, 31]` | **83** (80 insn diffs + 3 length diff) |\n')
s.append('| **Variant 12 (Reversed Store Order `mUnk790 = 0; mUnk792 = 0`)** | `mUnk790 = 0; mUnk792 = 0;` with ternary | NO (hoists `r29`) | 88 | `0x40` | `[29, 30, 31]` | **83** (80 insn diffs + 3 length diff) |\n')
s.append('| **Variant 13 (Local Scalar Variable for Stores)** | `s16 z = 0; mUnk792 = z; mUnk790 = z;` with ternary | NO (hoists `r29`) | 88 | `0x40` | `[29, 30, 31]` | **83** (80 insn diffs + 3 length diff) |\n')
s.append('| **Variant 14 (Variable Arm `(fBase_c*)mUnk770`)** | `fBase_c *base = (mUnk770 == 0) ? (fBase_c*)mUnk770 : fManager_c::searchBaseByID((fBaseID_e)mUnk770); if (base != 0) base->deleteRequest();` | NO (omits `li r3,0`) | 84 | `0x30` | `[30, 31]` | **49** (48 insn diffs + 1 length diff) |\n\n')

s.append('### 3.3. Systematic Rule-Out of the Four Proposed Levers\n\n')
s.append('1. **Lever 1: Type the null arm as an explicit pointer (`(fBase_c *)NULL`, `(fBase_c *)0`, `(void *)0`, `0L`)**\n')
s.append('   - *Result*: All tested pointer-cast variants compiled to the identical 88-word / frame `0x40` / GPR `[29, 30, 31]` object with 83 diffs.\n')
s.append('   - *Mechanism*: MWCC front-end evaluates null pointer constants in C++ AST to integer value 0 before global CSE. The type qualification is discarded during constant canonicalization, so global CSE sees the identical literal 0 on both sides of `UnKnownScoreSet`.\n\n')

s.append('2. **Lever 2: Write the two `sth` stores against a differently-typed zero (`(s16)0`, `(u16)0`, local variable, chain assignment, store reordering)**\n')
s.append('   - *Result*: All 6 variations evaluated identically at 88 words / frame `0x40` / GPR `[29, 30, 31]` with 83 diffs.\n')
s.append('   - *Mechanism*: 16-bit stores with constant 0 generate an intermediate representation node with constant value 0. MWCC cost analysis identifies 3 uses of constant 0 across a call (store to `0x792`, store to `0x790`, and ternary merge) against a threshold of 2 instructions for non-volatile register save/restore, thus unconditionally committing `r29`.\n\n')

s.append('3. **Lever 3: Move the ternary textual position relative to stores / calls**\n')
s.append('   - *Result*: Inverting condition polarity (`!= 0`) produced 87 words / frame `0x40` / GPR `[29, 30, 31]` (84 diffs); in-condition declaration produced 88 words (83 diffs).\n')
s.append('   - *Mechanism*: Flow-graph construction and basic block live-range analysis are position-independent across the `UnKnownScoreSet` call boundary.\n\n')

s.append('4. **Lever 4: Split the ternary into `if/else` assigning the same `fBase_c *` local in both arms**\n')
s.append('   - *Result*: Both standard and inverted `if/else` assignments produced identical code generation to the ternary (88 words / frame `0x40` / GPR `[29, 30, 31]` / 83 diffs).\n')
s.append('   - *Mechanism*: SSA translation collapses `if/else` assigning the same SSA phi-node variable into the exact same flow-graph merge as a ternary expression.\n\n')

s.append('---\n\n')

s.append('## 4. Work Order Item 2: Full Object Verification & Landed State\n\n')
s.append('Canonical source `d_enemy_toride_kokoopa.cpp` is built and verified with clean Variant A in place.\n')
s.append('`d_enemy_toride_kokoopa.o` and `draft_disasm.txt` are fresh and synchronized.\n\n')
s.append('- **Matched Status**: **248 / 251 matched (98.80%)**, **30,816 / 31,876 bytes (96.67%)**\n')
s.append('- **Zero Regressions**: All 248 matching functions remain 100% matched byte-for-byte.\n\n')

s.append('### Verbatim `fndiff.py --all` Output:\n')
s.append(ticks + '\n')
s.append(fndiff_all_raw + '\n')
s.append(ticks + '\n\n')

s.append('---\n\n')

s.append('## 5. Work Order Item 3: Header Manifest Decisions\n\n')
s.append('### 5.1. `d_actor_manager.hpp` — Offset Proof for `mpBossDemo`\n')
s.append('- **Decision**: **Keep promotion (split `mPad1[0x28]` -> `mPad1[0x18]` + `daBossDemo_c *mpBossDemo` + `mPad1b[0xC]`)**.\n')
s.append('- **Retail Evidence**:\n')
s.append('  - Function: `dEnTorideKokoopa_c::deadProc()` (`0x800A9F70`, size `0x4C` / 76 B / 19 instructions).\n')
s.append('  - Landing Status: **100% byte-identical match** in retail binary.\n')
s.append('  - Retail Disassembly (`auto_03_800A8710_text.txt:2181-2202`):\n')
s.append('```asm\n')
s.append('800A9F70: stwu  r1, -0x10(r1)\n')
s.append('800A9F74: mflr  r0\n')
s.append('800A9F78: stw   r0, 0x14(r1)\n')
s.append('800A9F7C: lwz   r12, 0x60(r3)                      ; vtable of this\n')
s.append('800A9F80: lwz   r12, 0x594(r12)                    ; deadVo()\n')
s.append('800A9F84: mtctr r12\n')
s.append('800A9F88: bctrl\n')
s.append('800A9F8C: lwz   r3, m_instance__11dActorMng_c@sda21(r0) ; load dActorMng_c::m_instance\n')
s.append('800A9F90: lwz   r3, 0x18(r3)                       ; <-- ACCESS AT OFFSET 0x18 of dActorMng_c\n')
s.append('800A9F94: cmpwi r3, 0x0                            ; check mpBossDemo != nullptr\n')
s.append('800A9F98: beq   .L_skip\n')
s.append('800A9F9C: lwz   r12, 0x60(r3)                      ; vtable of daBossDemo_c\n')
s.append('800A9FA0: lwz   r12, 0x11c(r12)                    ; stopBGM() vtable slot 0x11c\n')
s.append('800A9FA4: mtctr r12\n')
s.append('800A9FA8: bctrl\n')
s.append('.L_skip:\n')
s.append('800A9FAC: lwz   r0, 0x14(r1)\n')
s.append('800A9FB0: mtlr  r0\n')
s.append('800A9FB4: addi  r1, r1, 0x10\n')
s.append('800A9FB8: blr\n')
s.append('```\n')
s.append('- **Arithmetic & Layout**:\n')
s.append('  - `mPad1[0x28]` spans offsets `0x00`..`0x28` (`40` bytes).\n')
s.append('  - Split layout:\n')
s.append('    - `u8 mPad1[0x18];` (offsets `0x00`..`0x18`, `24` bytes)\n')
s.append('    - `daBossDemo_c *mpBossDemo;` (offsets `0x18`..`0x1C`, `4` bytes)\n')
s.append('    - `u8 mPad1b[0xC];` (offsets `0x1C`..`0x28`, `12` bytes)\n')
s.append('  - Total size: `24 + 4 + 12 = 40` bytes (`0x28`).\n')
s.append('  - **Offset-perturbing**: **NO**. Exactly size-neutral and validated by byte-exact codegen in `deadProc()`.\n\n')

s.append('### 5.2. `d_cc.hpp` `setKind`\n')
s.append('- **Decision**: **Drop `dCc_c::setKind` from promotion**.\n')
s.append('- **Evidence**: Grep across the entire codebase confirms `dCc_c::setKind` is completely unused in `d_enemy_toride_kokoopa.cpp` (and throughout all other TUs; only `dActor_c::setKind` exists in `d_actor.cpp`). It was an extraneous shadow declaration and should be dropped.\n\n')

s.append('---\n\n')

s.append('## 6. Constant Pool Verification (`poolcheck.py`)\n\n')
s.append('```\n')
s.append('177 pooled constants compared by VALUE across 250 paired functions\n')
s.append('0 mismatched, 0 could not be resolved on one side\n')
s.append('(248 pair(s) value-checked; 16 reference(s) skipped as the same named symbol on both sides; 381 float load(s) seen; 1 pair(s) skipped on length)\n')
s.append('COVERAGE: 248 of 488 target function(s) value-checked; 240 were not checked at all (unpaired, length-mismatched, or already differing).\n')
s.append('```\n')
s.append('Exit code: **0 (clean)**.\n\n')

s.append('---\n\n')

s.append('## 7. NOT REACHED\n\n')
s.append('**None**. All three numbered items in the round 30 work order have been fully executed, measured, verified, and reported.\n')

final_content = ''.join(s)

with open('GEMINI_RESPONSE.md', 'w', encoding='utf-8', newline='\n') as fh:
    fh.write(final_content.strip() + '\n')

print('Report written to GEMINI_RESPONSE.md, total bytes:', len(final_content))

