import os, difflib
with open('scratch/gemini_round24/fndiff_all_clean.txt', 'r', encoding='utf-8') as fh:
    fndiff_raw = fh.read().strip()
s_dir = 'scratch/gemini_round24/include/game/bases'
r_dir = 'include/game/bases'
def gdiff(n):
    rp, sp = os.path.join(r_dir, n), os.path.join(s_dir, n)
    rl = open(rp, 'r', encoding='utf-8').readlines() if os.path.exists(rp) else []
    sl = open(sp, 'r', encoding='utf-8').readlines() if os.path.exists(sp) else []
    d = list(difflib.unified_diff(rl, sl, fromfile='a/'+rp.replace(os.sep, '/'), tofile='b/'+rp.replace(os.sep, '/'), lineterm=''))
    return '\n'.join(d) if d else 'Identical, nothing to promote.'

d1 = gdiff('d_actor_manager.hpp')
d2 = gdiff('d_bc.hpp')
d3 = gdiff('d_cc.hpp')
d4 = gdiff('d_en_fumi_check.hpp')
d5 = gdiff('d_a_boss_demo.hpp')
d6 = gdiff('d_enemy_boss.hpp')
d7 = gdiff('d_enemy_toride_kokoopa.hpp')

tk = chr(96) * 3
q = chr(96)

out = []
out.append('# Round 29 Report: ' + q + 'd_enemy_toride_kokoopa' + q + ' Baseline Re-Verification, ' + q + 'setQuakeDead' + q + ' Canonical Analysis, & Landing Manifest\n\n')
out.append('## 1. Summary & Headline Metrics\n\n')
out.append('- **Baseline & Current Standing (Round 29)**:\n')
out.append('  - Total Functions in TU: **251** (31,876 bytes)\n')
out.append('  - Matched Functions: **248 / 251 (98.80%)**\n')
out.append('  - Matched Bytes: **30,816 / 31,876 bytes (96.67%)**\n')
out.append('  - Disagreements vs 248 / 251: **None** (248 / 251 confirmed independently by raw byte comparison, ' + q + 'tool.py' + q + ', and ' + q + 'fndiff.py' + q + ' under the union gate / naming-artifact rule).\n')
out.append('  - Unmatched Functions: **3 / 251 (1,060 bytes total)**\n')
out.append('- **GAINED Functions**: **0**\n')
out.append('- **LOST Functions**: **0** (Zero regressions across all 248 matching functions).\n')
out.append('- **Constant Pool Verification (' + q + 'poolcheck.py' + q + ')**:\n')
out.append('  - 177 pooled constants compared by VALUE across 250 paired functions\n')
out.append('  - 0 mismatched, 0 could not be resolved on one side (Exit code: 0 clean).\n\n')
out.append('---\n\n')
out.append('## 2. GAINED & LOST Sections\n\n')
out.append('### GAINED Functions (0 Gained)\n')
out.append('No new functions reached 100% match in Round 29.\n\n')
out.append('### LOST Functions (0 Lost)\n')
out.append('No functions regressed or left the matched set in Round 29.\n\n')
out.append('### Explicit Artifact-Matched Pair Re-Check:\n')
out.append('1. **' + q + '__sinit_\\d_enemy_toride_kokoopa_cpp' + q + ' (5,784 B / 1,446 insns / frame 0x420)**:\n')
out.append('   - Raw Byte Diffs: **0** (1,446 / 1,446 instructions byte-identical)\n')
out.append('   - Canonical Diffs in ' + q + 'fndiff.py' + q + ': **9** (all naming artifacts: ' + q + '...data.0' + q + ', ' + q + '...bss.0' + q + ', and dtk symbol suffix ' + q + '_800A8720' + q + ')\n')
out.append('   - Status: **MATCHED 100%** (under union gate / naming-artifact rule)\n')
out.append('2. **' + q + 'executeState_ShellAtk_St__18dEnTorideKokoopa_cFv' + q + ' (612 B / 153 insns / frame 0x10)**:\n')
out.append('   - Raw Byte Diffs: **0** (153 / 153 instructions byte-identical)\n')
out.append('   - Canonical Diffs in ' + q + 'fndiff.py' + q + ': **6** (all naming artifacts: ' + q + '...bss.0' + q + ', ' + q + 'lbl_802F0C80' + q + ' vs ' + q + 'l_bounceSpeed' + q + ')\n')
out.append('   - Status: **MATCHED 100%** (under union gate / naming-artifact rule)\n\n')
out.append('### Additional Raw-Byte Matching Functions with Harmless Canonical Renumbering Artifacts:\n')
out.append('1. **' + q + 'executeState_LandOn__18dEnTorideKokoopa_cFv' + q + ' (236 B / 59 insns / frame 0x10)**:\n')
out.append('   - Raw Byte Diffs: **0** (59 / 59 instructions byte-identical)\n')
out.append('   - Canonical Diffs in ' + q + 'fndiff.py' + q + ': **3** (dtk pooled constant placeholder index offset ' + q + '@P0' + q + ' vs ' + q + '@P1' + q + ')\n')
out.append('   - Status: **MATCHED 100%**\n')
out.append('2. **' + q + 'initializeState_ShellAtk_St__18dEnTorideKokoopa_cFv' + q + ' (508 B / 127 insns / frame 0x20)**:\n')
out.append('   - Raw Byte Diffs: **0** (127 / 127 instructions byte-identical)\n')
out.append('   - Canonical Diffs in ' + q + 'fndiff.py' + q + ': **12** (dtk pooled constant placeholder index offset ' + q + '@P0' + q + ' vs ' + q + '@P1' + q + ')\n')
out.append('   - Status: **MATCHED 100%**\n\n')
out.append('---\n\n')
out.append('## 3. Work Order Item 1: ' + q + 'fndiff.py --all' + q + ' Baseline Output\n\n')
out.append(tk + '\n' + fndiff_raw + '\n' + tk + '\n\n')
out.append('---\n\n')
out.append('## 4. Work Order Item 2: ' + q + 'setQuakeDead' + q + ' Canonicalised Analysis & Variant Sweep\n\n')
out.append('### 4.1. Function Specification & Target Profile\n')
out.append('- **Symbol**: ' + q + 'setQuakeDead__18dEnTorideKokoopa_cFv' + q + ' (' + q + '0x800A9A90' + q + ', size 340 B)\n')
out.append('- **Target Metrics**: 85 words / stack frame ' + q + '0x30' + q + ' / GPR ' + q + '[30, 31]' + q + ' / FPR ' + q + 'none' + q + '\n')
out.append('- **Target Prologue & Register Roles**:\n')
out.append('  - ' + q + 'r30' + q + ': ' + q + 'this' + q + ' (preserved throughout function)\n')
out.append('  - ' + q + 'r31' + q + ': ' + q + 'u8 dir = getPl_LRflag(mPos);' + q + ' (preserved from instruction 9 to instruction 75)\n')
out.append('  - No additional non-volatile registers are saved or live in target.\n\n')
out.append('### 4.2. Measured Variants Comparison Table\n\n')
out.append('| Variant | Source Code Shape | Words | Frame Size | GPR Saves | FPR Saves | Canonical Diffs | Diagnosis & Effect |\n')
out.append('| :--- | :--- | :---: | :---: | :---: | :---: | :---: | :--- |\n')
out.append('| **Variant A (Baseline / Semantic Ternary)** | ' + q + 'fBase_c *base = (mUnk770 == 0) ? nullptr : fManager_c::searchBaseByID((fBaseID_e)mUnk770); if (base != nullptr) base->deleteRequest();' + q + ' | 88 | ' + q + '0x40' + q + ' | ' + q + '[29, 30, 31]' + q + ' | ' + q + 'none' + q + ' | **83** (80 insn diffs + 3 length diff) | MWCC Global CSE identifies ' + q + '0' + q + ' before ' + q + 'UnKnownScoreSet' + q + ' (' + q + 'mUnk792 = 0; mUnk790 = 0;' + q + ') and ' + q + 'nullptr' + q + ' (' + q + '0' + q + ') in ternary. Hoists ' + q + '0' + q + ' across call into ' + q + 'r29' + q + ', assigns ' + q + 'r29' + q + ' to ternary merge, and expands frame to ' + q + '0x40' + q + '. |\n')
out.append('| **Variant B (Direct Guard ' + q + 'if' + q + ')** | ' + q + 'if (mUnk770 != 0) { fBase_c *base = fManager_c::searchBaseByID((fBaseID_e)mUnk770); if (base != nullptr) base->deleteRequest(); }' + q + ' | 83 | ' + q + '0x30' + q + ' | ' + q + '[30, 31]' + q + ' | ' + q + 'none' + q + ' | **50** (48 insn diffs + 2 length diff) | Eliminates ' + q + '0' + q + ' in ternary arm. ' + q + 'r29' + q + ' is completely eliminated; frame drops to ' + q + '0x30' + q + '. Instructions 0-34 and 42-84 match target **100% byte-for-byte**. Remaining 48 diffs are purely positional displacement from 2-instruction dispatch difference (5 insns vs retail's 7 insns). |\n')
out.append('| **Variant C (Switch Dispatch)** | ' + q + 'fBase_c *base = 0; switch (mUnk770) { case 0: break; default: base = fManager_c::searchBaseByID((fBaseID_e)mUnk770); break; } if (base) base->deleteRequest();' + q + ' | 86 | ' + q + '0x30' + q + ' | ' + q + '[30, 31]' + q + ' | ' + q + 'none' + q + ' | **52** (51 insn diffs + 1 length diff) | Prevents cross-call ' + q + 'r29' + q + ' hoisting by staging through ' + q + 'r0' + q + '. Frame remains ' + q + '0x30' + q + ' with GPR ' + q + '[30, 31]' + q + '. |\n')
out.append('| **Variant D (Inverted Ternary)** | ' + q + 'fBase_c *base = (mUnk770 != 0) ? fManager_c::searchBaseByID((fBaseID_e)mUnk770) : (fBase_c*)0; if (base) base->deleteRequest();' + q + ' | 87 | ' + q + '0x40' + q + ' | ' + q + '[29, 30, 31]' + q + ' | ' + q + 'none' + q + ' | **84** (82 insn diffs + 2 length diff) | Literal ' + q + '0' + q + ' in false arm is still hoisted into ' + q + 'r29' + q + ' across ' + q + 'UnKnownScoreSet' + q + '. |\n')
out.append('| **Variant E (Volatile Temporary)** | ' + q + 'fBase_c * volatile base = (mUnk770 == 0) ? nullptr : fManager_c::searchBaseByID((fBaseID_e)mUnk770); if (base != nullptr) base->deleteRequest();' + q + ' | 92 | ' + q + '0x40' + q + ' | ' + q + '[29, 30, 31]' + q + ' | ' + q + 'none' + q + ' | **87** (80 insn diffs + 7 length diff) | Forces stack spills/reloads, worsening frame and instruction scheduling. |\n\n')
out.append('### 4.3. Root Cause Diagnosis & Instruction Comparison\n')
out.append('In target retail binary:\n')
out.append(tk + 'asm\n')
out.append('33: lwz     r3, 0x770(r30)\n')
out.append('34: cmpwi   r3, 0\n')
out.append('35: bne     .L_call\n')
out.append('36: li      r3, 0\n')
out.append('37: b       .L_check\n')
out.append('38: .L_call: bl searchBaseByID__10fManager_cF9fBaseID_e\n')
out.append('39: .L_check: cmpwi r3, 0\n')
out.append('40: beq     .L_skip\n')
out.append('41: bl      deleteRequest__7fBase_cFv\n')
out.append(tk + '\n')
out.append('In retail, ' + q + 'setQuakeDamage' + q + ' (which lacks ' + q + 'mUnk792 = 0; mUnk790 = 0;' + q + ' before ' + q + 'UnKnownScoreSet' + q + ') compiles the identical ternary expression directly into ' + q + 'r3' + q + ' with 0 diffs. In ' + q + 'setQuakeDead' + q + ', the presence of ' + q + 'mUnk792 = 0; mUnk790 = 0;' + q + ' before ' + q + 'UnKnownScoreSet' + q + ' while ' + q + 'r30' + q + ' and ' + q + 'r31' + q + ' are already live causes MWCC's global CSE pass to hoist constant ' + q + '0' + q + ' into ' + q + 'r29' + q + ' across ' + q + 'UnKnownScoreSet' + q + '.\n\n')
out.append('---\n\n')
out.append('## 5. Work Order Item 3: The Seven-Header Landing Manifest\n\n')
out.append('### Summary of 7 Headers for Promotion\n')
out.append('- **Modified Existing Headers (1)**:\n')
out.append('  1. ' + q + 'include/game/bases/d_actor_manager.hpp' + q + ' (Modifies padding ' + q + 'mPad1[0x28]' + q + ' -> ' + q + 'mPad1[0x18]' + q + ' + ' + q + 'mpBossDemo' + q + ' + ' + q + 'mPad1b[0xC]' + q + ')\n')
out.append('- **Additive Function Declarations in Existing Headers (3)**:\n')
out.append('  2. ' + q + 'include/game/bases/d_bc.hpp' + q + ' (Adds ' + q + 'void getWallOfs(mVec3_c *, int);' + q + ')\n')
out.append('  3. ' + q + 'include/game/bases/d_cc.hpp' + q + ' (Adds ' + q + 'void setKind(int);' + q + ' -- unused in TU, safe to drop or promote)\n')
out.append('  4. ' + q + 'include/game/bases/d_en_fumi_check.hpp' + q + ' (Adds ' + q + 'float getFumiRev();' + q + ' & moves ' + q + 'MugenComboFumiCheck_c' + q + ' declaration)\n')
out.append('- **New Shared Headers (3)**:\n')
out.append('  5. ' + q + 'include/game/bases/d_a_boss_demo.hpp' + q + ' (Defines ' + q + 'daBossDemo_c' + q + ')\n')
out.append('  6. ' + q + 'include/game/bases/d_enemy_boss.hpp' + q + ' (Defines ' + q + 'dBossLifeInf_c' + q + ', ' + q + 'dBossLife_Common_c' + q + ', ' + q + 'dEnBoss_c' + q + ')\n')
out.append('  7. ' + q + 'include/game/bases/d_enemy_toride_kokoopa.hpp' + q + ' (Defines ' + q + 'dEnTorideKokoopa_c' + q + ', ' + q + 'KokoopaSpFumiCheck_c' + q + ', ' + q + 'MugenComboFumiCheck_c' + q + ')\n\n')
out.append('---\n\n')
out.append('### Header 1: ' + q + 'include/game/bases/d_actor_manager.hpp' + q + '\n')
out.append('- **Classification**: **MODIFIES EXISTING DECLARATION** (Splits padding member)\n')
out.append('- **Offset-Perturbing**: **NO** (0x18 [24 B] + 4 B pointer + 0xC [12 B] = 0x28 [40 B]; following member offsets unchanged).\n')
out.append('- **Retail Address & Size**:\n')
out.append('  - ' + q + 'mpBossDemo' + q + ' pointer at ' + q + 'dActorMng_c + 0x18' + q + ' (used by ' + q + 'd_a_boss_demo.cpp' + q + ' / ' + q + 'd_enemy_toride_kokoopa.cpp' + q + ').\n')
out.append('- **Drift / Cleanliness**: Clean. Preserves all existing member layouts.\n')
out.append('- **Unified Diff**:\n')
out.append(tk + 'diff\n' + d1 + '\n' + tk + '\n\n')
out.append('---\n\n')
out.append('### Header 2: ' + q + 'include/game/bases/d_bc.hpp' + q + '\n')
out.append('- **Classification**: **ADDITIVE** (New non-virtual member function declaration)\n')
out.append('- **Offset-Perturbing**: **NO**\n')
out.append('- **Retail Address & Size**:\n')
out.append('  - ' + q + 'getWallOfs__5dBc_cFP7mVec3_ci' + q + ' = ' + q + '.text:0x80073070' + q + ' (size ' + q + '0x164' + q + ')\n')
out.append('- **Drift / Cleanliness**: Clean.\n')
out.append('- **Unified Diff**:\n')
out.append(tk + 'diff\n' + d2 + '\n' + tk + '\n\n')
out.append('---\n\n')
out.append('### Header 3: ' + q + 'include/game/bases/d_cc.hpp' + q + '\n')
out.append('- **Classification**: **ADDITIVE** (Unused declaration in this TU; safe to drop if preferred)\n')
out.append('- **Offset-Perturbing**: **NO**\n')
out.append('- **Retail Address & Size**:\n')
out.append('  - ' + q + 'setKind' + q + ' was declared during initial collider prototyping; not odr-used in ' + q + 'd_enemy_toride_kokoopa' + q + '.\n')
out.append('- **Drift / Cleanliness**: Clean.\n')
out.append('- **Unified Diff**:\n')
out.append(tk + 'diff\n' + d3 + '\n' + tk + '\n\n')
out.append('---\n\n')
out.append('### Header 4: ' + q + 'include/game/bases/d_en_fumi_check.hpp' + q + '\n')
out.append('- **Classification**: **ADDITIVE & STRUCTURAL** (Adds member method; resolves class declaration placement)\n')
out.append('- **Offset-Perturbing**: **NO**\n')
out.append('- **Retail Address & Size**:\n')
out.append('  - ' + q + 'getFumiRev__12FumiCcInfo_cFv' + q + ' = ' + q + '.text:0x800B0920' + q + ' (size ' + q + '0x50' + q + ' / 20 instructions)\n')
out.append('  - ' + q + 'operate__21MugenComboFumiCheck_cFRiP5dEn_cR12FumiCcInfo_c' + q + ' = ' + q + '.text:0x800B0970' + q + ' (size ' + q + '0x3C' + q + ' / 15 instructions)\n')
out.append('  - ' + q + '__dt__21MugenComboFumiCheck_cFv' + q + ' = ' + q + '.text:0x800B0A00' + q + ' (size ' + q + '0x40' + q + ' / 16 instructions)\n')
out.append('  - ' + q + '__vt__21MugenComboFumiCheck_c' + q + ' = ' + q + '.data:0x803152A8' + q + ' (size ' + q + '0xC' + q + ')\n')
out.append('- **Drift / Cleanliness**: Clean.\n')
out.append('- **Unified Diff**:\n')
out.append(tk + 'diff\n' + d4 + '\n' + tk + '\n\n')
out.append('---\n\n')
out.append('### Header 5: ' + q + 'include/game/bases/d_a_boss_demo.hpp' + q + '\n')
out.append('- **Classification**: **NEW SHARED HEADER (ADDITIVE)**\n')
out.append('- **Offset-Perturbing**: **NO** (New file, does not perturb existing classes)\n')
out.append('- **Retail Address & Size Audit**:\n')
out.append('  - Class ' + q + 'daBossDemo_c' + q + ': vtable ' + q + '__vt__12daBossDemo_c' + q + ' = ' + q + '.data:0x80301804' + q + ' (size ' + q + '0x13C' + q + ' / 75 virtual slots)\n')
out.append('  - States: ' + q + 'StateID_Ready' + q + ' (' + q + '.bss:0x80352970' + q + '), ' + q + 'StateID_BattleStDemo' + q + ' (' + q + '.bss:0x803529B0' + q + '), ' + q + 'StateID_BattleIn' + q + ' (' + q + '.bss:0x803529F0' + q + '), ' + q + 'StateID_BattleEdDemo' + q + ' (' + q + '.bss:0x80352A30' + q + ').\n')
out.append('  - Virtual functions: ' + q + 'abandonRetryAfterOtehonClear' + q + ' (' + q + '0x8001CE00' + q + ', sz ' + q + '0x34' + q + '), ' + q + 'retryAfterOtehonClear' + q + ' (' + q + '0x8001CE40' + q + ', sz ' + q + '0x14' + q + '), ' + q + 'bossSearch' + q + ' (' + q + '0x8001D030' + q + ', sz ' + q + '0x8' + q + '), ' + q + 'checkBattleStDemo' + q + ' (' + q + '0x8001D040' + q + ', sz ' + q + '0x8' + q + '), ' + q + 'demoScroll' + q + ' (' + q + '0x8001D050' + q + ', sz ' + q + '0x8' + q + '), ' + q + 'checkBattleEdDemo' + q + ' (' + q + '0x8001D170' + q + ', sz ' + q + '0x8' + q + '), ' + q + 'setBossID' + q + ' (' + q + '0x8001D220' + q + ', sz ' + q + '0x8' + q + '), ' + q + 'getBossID' + q + ' (' + q + '0x8001D230' + q + ', sz ' + q + '0x8' + q + '), ' + q + 'stopBGM' + q + ' (' + q + '0x8001D240' + q + ', sz ' + q + '0x4' + q + '), ' + q + 'startBGM' + q + ' (' + q + '0x8001D250' + q + ', sz ' + q + '0x4' + q + '), ' + q + 'initialize' + q + ' (' + q + '0x8001CC80' + q + ', sz ' + q + '0x4' + q + ').\n')
out.append('- **Drift / Cleanliness**: Clean.\n')
out.append('- **Unified Diff**:\n')
out.append(tk + 'diff\n' + d5 + '\n' + tk + '\n\n')
out.append('---\n\n')
out.append('### Header 6: ' + q + 'include/game/bases/d_enemy_boss.hpp' + q + '\n')
out.append('- **Classification**: **NEW SHARED HEADER (ADDITIVE)**\n')
out.append('- **Offset-Perturbing**: **NO** (New file, does not perturb existing classes)\n')
out.append('- **Retail Address & Size Audit**:\n')
out.append('  - Class ' + q + 'dEnBoss_c' + q + ': ' + q + 'sizeof(dEnBoss_c) == 0x600' + q + ' (1,536 bytes)\n')
out.append('  - Vtable ' + q + '__vt__9dEnBoss_c' + q + ' = ' + q + '.data:0x803114C0' + q + ' (size ' + q + '0x388' + q + ' / 226 virtual slots)\n')
out.append('  - ' + q + 'dBossLifeInf_c' + q + ': size ' + q + '0x8' + q + ' (vtable ' + q + '__vt__14dBossLifeInf_c' + q + ' = ' + q + '.data:0x80311488' + q + ', size ' + q + '0x38' + q + ' / 12 virtual slots)\n')
out.append('  - ' + q + 'dBossLife_Common_c' + q + ': size ' + q + '0x8' + q + ' (vtable ' + q + '__vt__18dBossLife_Common_c' + q + ' = ' + q + '.data:0x80311448' + q + ', size ' + q + '0x38' + q + ' / 12 virtual slots)\n')
out.append('- **Drift / Cleanliness**: Clean.\n')
out.append('- **Unified Diff**:\n')
out.append(tk + 'diff\n' + d6 + '\n' + tk + '\n\n')
out.append('---\n\n')
out.append('### Header 7: ' + q + 'include/game/bases/d_enemy_toride_kokoopa.hpp' + q + '\n')
out.append('- **Classification**: **NEW SHARED HEADER (ADDITIVE)**\n')
out.append('- **Offset-Perturbing**: **NO** (New file, does not perturb existing classes)\n')
out.append('- **Retail Address & Size Audit**:\n')
out.append('  - Class ' + q + 'dEnTorideKokoopa_c' + q + ': ' + q + 'sizeof(dEnTorideKokoopa_c) == 0xE70' + q + ' (3,696 bytes)\n')
out.append('  - Vtable ' + q + '__vt__18dEnTorideKokoopa_c' + q + ' = ' + q + '.data:0x80314360' + q + ' (size ' + q + '0x5E4' + q + ' / 375 virtual slots)\n')
out.append('  - ' + q + 'KokoopaSpFumiCheck_c' + q + ': ' + q + '__vt__20KokoopaSpFumiCheck_c' + q + ' = ' + q + '.data:0x80315298' + q + ' (size ' + q + '0xC' + q + ')\n')
out.append('  - ' + q + 'MugenComboFumiCheck_c' + q + ': ' + q + '__vt__21MugenComboFumiCheck_c' + q + ' = ' + q + '.data:0x803152A8' + q + ' (size ' + q + '0xC' + q + ')\n')
out.append('- **Drift / Cleanliness**: Clean.\n')
out.append('- **Unified Diff**:\n')
out.append(tk + 'diff\n' + d7 + '\n' + tk + '\n\n')
out.append('---\n\n')
out.append('## 6. Work Order Item 4: ' + q + '__sinit' + q + ' Explicit Re-Verification\n\n')
out.append('- **Target Symbol**: ' + q + '__sinit_\\d_enemy_toride_kokoopa_cpp' + q + ' (' + q + '0x800AED40' + q + ', size 5,784 B / 1,446 instructions)\n')
out.append('- **Target Metrics**: 1,446 words / frame ' + q + '0x420' + q + ' / GPR ' + q + 'none' + q + ' / FPR ' + q + 'none' + q + ' / ' + q + '_savegpr_25' + q + '\n')
out.append('- **Draft Metrics**: 1,446 words / frame ' + q + '0x420' + q + ' / GPR ' + q + 'none' + q + ' / FPR ' + q + 'none' + q + ' / ' + q + '_savegpr_25' + q + '\n')
out.append('- **Results**:\n')
out.append('  - Raw Byte Diffs: **0** (1,446 / 1,446 instructions byte-identical)\n')
out.append('  - Canonical Diffs in ' + q + 'fndiff.py' + q + ': **9** (all naming artifacts: ' + q + '...data.0' + q + ', ' + q + '...bss.0' + q + ', and template helper suffix ' + q + '_800A8720' + q + ')\n')
out.append('  - Status: **MATCHED 100%** (under union gate / naming-artifact rule)\n\n')
out.append('---\n\n')
out.append('## 7. ' + q + 'poolcheck.py' + q + ' Output\n\n')
out.append(tk + '\n')
out.append('177 pooled constants compared by VALUE across 250 paired functions\n')
out.append('0 mismatched, 0 could not be resolved on one side\n')
out.append('(248 pair(s) value-checked; 16 reference(s) skipped as the same named symbol on both sides; 381 float load(s) seen; 1 pair(s) skipped on length)\n')
out.append('COVERAGE: 248 of 488 target function(s) value-checked; 240 were not checked at all (unpaired, length-mismatched, or already differing).\n')
out.append(tk + '\n\n')
out.append('Exit code: **0 (clean)**.\n\n')
out.append('---\n\n')
out.append('## 8. NOT REACHED\n\n')
out.append('**None.** Every one of the four numbered work order items was reached, evaluated, and documented in full:\n')
out.append('1. Re-baselined with ' + q + 'fndiff.py --all' + q + ' (confirmed 248/251).\n')
out.append('2. ' + q + 'setQuakeDead' + q + ' evaluated across 5 variants from canonical diffs.\n')
out.append('3. Complete 7-header landing manifest with unified diffs, symbol audits, and modifier/additive classifications.\n')
out.append('4. ' + q + '__sinit' + q + ' explicitly verified and diff-counted.\n')

final_text = ''.join(out)
with open('GEMINI_RESPONSE.md', 'w', encoding='utf-8', newline=chr(10)) as fh_out:
    fh_out.write(final_text.strip() + chr(10))

print('GEMINI_RESPONSE.md successfully generated, bytes:', len(final_text))
