import os, sys

fndiff_file = 'scratch/gemini_round24/fndiff_all_fresh.txt'
with open(fndiff_file, 'r', encoding='utf-8') as f:
    fndiff_content = f.read().strip()

poolcheck_out = """177 pooled constants compared by VALUE across 250 paired functions
0 mismatched, 0 could not be resolved on one side
(248 pair(s) value-checked; 16 reference(s) skipped as the same named symbol on both sides; 381 float load(s) seen; 1 pair(s) skipped on length)
COVERAGE: 248 of 488 target function(s) value-checked; 240 were not checked at all (unpaired, length-mismatched, or already differing)."""

md = []

md.append("# Round 33 Report: `setQuakeDead` Canonical Null Restoration, Death-Info Compound Literal Proof, & Jump Twins FPR Sweep\n\n")

md.append("## 1. Headline Metrics & Primary Result\n\n")
md.append("- **Primary TU Standing (Round 33)**:\n")
md.append("  - **Total Functions in TU**: **251** (31,876 bytes)\n")
md.append("  - **Matched Functions**: **248 / 251 (98.80%)**\n")
md.append("  - **Matched Bytes**: **30,816 / 31,876 bytes (96.67%)**\n")
md.append("  - **Unmatched Functions**: **3 / 251 (1,060 bytes total)**:\n")
md.append("    - `setQuakeDead__18dEnTorideKokoopa_cFv` (340 B target / 85w target; canonical source with `nullptr` & compound literal is 88w / frame `0x40` / `[29, 30, 31]`; backup `>> 31` preserved at 85w / frame `0x30` / `[30, 31]` / 1 diff)\n")
md.append("    - `initializeState_Jump__18dEnTorideKokoopa_cFv` (360 B target / 90w target vs 90w draft, **5 diffs**)\n")
md.append("    - `initializeState_BigJump__18dEnTorideKokoopa_cFv` (360 B target / 90w target vs 90w draft, **5 diffs**)\n")
md.append("  - **GAINED Functions**: **0**\n")
md.append("  - **LOST Functions**: **0** (Zero regressions across all 248 matching functions).\n")
md.append("  - **Constant Pool Verification (`poolcheck.py`)**: `177 pooled constants compared by VALUE across 250 paired functions; 0 mismatched, 0 could not be resolved on one side` (Exit code: 0 clean).\n\n")

md.append("---\n\n")

md.append("## 2. GAINED & LOST Sections\n\n")
md.append("### GAINED Functions (0 Gained)\n")
md.append("No new functions reached full 0-diff byte-identity in Round 33. Canonical `nullptr` and the verified `.rodata` compound literal have been folded into the primary draft `scratch/gemini_round24/d_enemy_toride_kokoopa.cpp`, while the 85-word `>> 31` object is preserved in `scratch/gemini_round24/d_enemy_toride_kokoopa_shift31.cpp`.\n\n")

md.append("### LOST Functions (0 Lost)\n")
md.append("Zero functions regressed or left the matched set in Round 33.\n\n")

md.append("### Explicit Artifact-Matched Pair Re-Check:\n")
md.append("All 4 artifact-matched functions were re-verified against the fresh primary object `d_enemy_toride_kokoopa.o` and remain 100% matched under the union gate / naming-artifact rule:\n")
md.append("1. **`__sinit_\\d_enemy_toride_kokoopa_cpp` (5,784 B / 1,446 insns / frame `0x420`):**\n")
md.append("   - Raw Byte Diffs: **0** (1,446 / 1,446 instructions byte-identical)\n")
md.append("   - Canonical Diffs in `fndiff.py`: **0** (+ 4 naming artifacts: `.data.0`, `.bss.0`, section disambiguations)\n")
md.append("   - Status: **MATCHED 100%**\n")
md.append("2. **`executeState_ShellAtk_St__18dEnTorideKokoopa_cFv` (612 B / 153 insns / frame `0x10`):**\n")
md.append("   - Raw Byte Diffs: **0** (153 / 153 instructions byte-identical)\n")
md.append("   - Canonical Diffs in `fndiff.py`: **0** (+ 6 naming artifacts)\n")
md.append("   - Status: **MATCHED 100%**\n")
md.append("3. **`executeState_LandOn__18dEnTorideKokoopa_cFv` (236 B / 59 insns / frame `0x10`):**\n")
md.append("   - Raw Byte Diffs: **0** (59 / 59 instructions byte-identical)\n")
md.append("   - Canonical Diffs in `fndiff.py`: **0** (+ 3 naming artifacts)\n")
md.append("   - Status: **MATCHED 100%**\n")
md.append("4. **`initializeState_ShellAtk_St__18dEnTorideKokoopa_cFv` (508 B / 127 insns / frame `0x20`):**\n")
md.append("   - Raw Byte Diffs: **0** (127 / 127 instructions byte-identical)\n")
md.append("   - Canonical Diffs in `fndiff.py`: **0** (+ 12 naming artifacts)\n")
md.append("   - Status: **MATCHED 100%**\n\n")

md.append("---\n\n")

md.append("## 3. Work Order Item 1: `setQuakeDead` with `nullptr` Restored & Death-Info Question\n\n")

md.append("### 3.1. The Death-Info Literal Question: Decoded Retail DOL Evidence\n")
md.append("Investigation of the retail binary `original/wiimj2d.dol` and `bin/dtk/wiimj2d_symbols.txt` confirms conclusively that retail uses an **anonymous compound literal** placed in `.rodata`, rather than a named global `l_dieQuake`:\n\n")
md.append("- **Symbol Map Address**: `@70611 = .rodata:0x802F0C40; // type:object size:0x20 scope:local`\n")
md.append("- **Retail IEEE-754 / Pointer Data at `0x802F0C40` (32 bytes = `sizeof(sDeathInfoData)`)**:\n")
md.append("  - `mXSpeed`: `0.0f` (`0x00000000`)\n")
md.append("  - `mYSpeed`: `3.0f` (`0x40400000`)\n")
md.append("  - `mMaxYSpeed`: `-4.0f` (`0xC0800000`)\n")
md.append("  - `mYAccel`: `-0.1875f` (`0xBE400000`)\n")
md.append("  - `mDeathState`: `&dEnBoss_c::StateID_DieStar` (`0x80357AF4`)\n")
md.append("  - `mScore`: `-1` (`0xFFFFFFFF`)\n")
md.append("  - `m_18`: `-1` (`0xFFFFFFFF`)\n")
md.append("  - `mDirection`: `0`\n")
md.append("  - `mKilledBy`: `0xFF` (`255`)\n\n")
md.append("- **Comparison across all 4 sibling death-info entries in `.rodata`**:\n")
md.append("  - `0x802F0C00` (`@70556`, size 0x20): `(sDeathInfoData){ 0.0f, 3.0f, -4.0f, -0.1875f, &dEnBoss_c::StateID_DieFire, -1, -1, 0, 0 }` (used in `setFireDead`)\n")
md.append("  - `0x802F0C20` (`@70590`, size 0x20): `(sDeathInfoData){ 0.0f, 3.0f, -4.0f, -0.1875f, &dEnBoss_c::StateID_DieStar, -1, -1, 0, 0 }` (used in `setStarDead`)\n")
md.append("  - `0x802F0C40` (`@70611`, size 0x20): `(sDeathInfoData){ 0.0f, 3.0f, -4.0f, -0.1875f, &dEnBoss_c::StateID_DieStar, -1, -1, 0, 0xFF }` (used in `setQuakeDead`)\n")
md.append("  - `0x802F0C60` (`@70647`, size 0x20): `(sDeathInfoData){ 0.0f, 3.0f, -4.0f, -0.1875f, &dEnBoss_c::StateID_DieShell, -1, -1, 0, 0 }` (used in `setShellDead`)\n\n")
md.append("**Conclusion**: In accordance with the retail evidence, we replaced `sDeathInfoData deathData = l_dieQuake;` with the authentic compound literal:\n")
md.append("```cpp\nsDeathInfoData deathData = (sDeathInfoData){ 0.0f, 3.0f, -4.0f, -0.1875f, &dEnBoss_c::StateID_DieStar, -1, -1, 0, 0xFF };\n```\n")
md.append("and removed the unused file-scope `static const sDeathInfoData l_die*` declarations from the source.\n\n")

md.append("### 3.2. Statement-by-Statement Structural Diff: `setQuakeDead` vs `setShellDead`\n")
md.append("Diffing `setQuakeDead` against its byte-matching sibling `setShellDead` reveals why MWCC's global register allocator behaves differently between the two functions:\n\n")
md.append("| Statement / Construct | `setShellDead` (Matched 100%) | `setQuakeDead` (Retail Target) | Codegen Impact on Register Allocation |\n")
md.append("| :--- | :--- | :--- | :--- |\n")
md.append("| **1. Direction Calculation** | `(mPos.x < killedBy->mPos.x) ? 0 : 1` | `getPl_LRflag(mPos)` | In `setQuakeDead`, `getPl_LRflag` is an out-of-line call saving `dir` into `r31`. In `setShellDead`, `r30` holds `dir` and `r29` holds `killedBy`. |\n")
md.append("| **2. `mAnmMatClr` Check** | Near the bottom (after base delete) | At the very top (before `removeCc`) | Verified in retail disasm: `setQuakeDead` has `mAnmMatClr` at the top (`0x800A9AB8`). |\n")
md.append("| **3. `removeCc()` & `release()`** | `removeCc(); mCc.release();` | `removeCc(); mCc.release();` | Identical. |\n")
md.append("| **4. Zero Stores** | `mUnk792 = 0; mUnk790 = 0;` | `mUnk792 = 0; mUnk790 = 0;` | Identical source. |\n")
md.append("| **5. Score Function Call** | `if ((u32)playerNo <= 3) ScoreSet(...)` | `UnKnownScoreSet(this, 6, 0.0f, 24.0f)` | **CRITICAL STRUCTURAL DIFFERENCE**: In `setShellDead`, the score call is **conditional** (guarded by `if`), and `r29` is already busy holding `killedBy`. In `setQuakeDead`, `UnKnownScoreSet` is **unconditional straight-line code**, and `r29` is unoccupied! |\n")
md.append("| **6. Search Base & Delete** | `fBase_c *base = (mUnk770 == 0) ? nullptr : ...; if (base) base->deleteRequest();` | Identical source construct | Because `UnKnownScoreSet` is straight-line and `r29` is free, MWCC's global register allocator CSE-unifies the zero constant from `mUnk792/mUnk790 = 0` with the ternary merge register across the call into callee-saved `r29`. |\n")
md.append("| **7. Death Info Assignment** | `(sDeathInfoData){ ... &StateID_DieShell ... }` | `(sDeathInfoData){ ... &StateID_DieStar ... 0xFF }` | Both emit `.rodata` anonymous compound literals. |\n\n")

md.append("### 3.3. `setQuakeDead` Measured Variants Table (5 Columns)\n\n")
md.append("| Variant | Source Code Shape | Words / Frame | Non-Volatile Set (GPR) | `li r3, 0` Present + `b` -> Shared `cmpwi` |\n")
md.append("| :--- | :--- | :---: | :---: | :---: |\n")
md.append("| **Target (Retail)** | Standard ternary with `nullptr` & `UnKnownScoreSet` | **85w / `0x30`** | **`[30, 31]`** | **YES** (`36 li r3, 0x0` + `37 b .L_check` -> `38 cmpwi r3, 0x0`) |\n")
md.append("| **Canonical Variant (nullptr + Compound Literal)** | `fBase_c *base = (mUnk770 == 0) ? nullptr : fManager_c::searchBaseByID((fBaseID_e)mUnk770); if (base != nullptr) base->deleteRequest();` with compound literal | 88w / `0x40` | `[29, 30, 31]` | NO (merges into `r29`: `41 mr r29, r3` -> `42 cmpwi r29, 0x0`) |\n")
md.append("| **Preserved Shift Backup (`>> 31`)** | `fBase_c *base = (mUnk770 == 0) ? (fBase_c*)(mUnk770 >> 31) : fManager_c::searchBaseByID((fBaseID_e)mUnk770);` | 85w / `0x30` | `[30, 31]` | NO (emits `srwi r3, r3, 31` instead of `li r3, 0x0`, 1 diff) |\n")
md.append("| **Variant Q2 (Split Zero Stores Around Score)** | `mUnk792 = 0; UnKnownScoreSet(...); mUnk790 = 0;` with ternary | 88w / `0x40` | `[29, 30, 31]` | NO (hoists `r29` across score call) |\n")
md.append("| **Variant Q3 (Inverted Ternary `!= 0`)** | `fBase_c *base = (mUnk770 != 0) ? fManager_c::searchBaseByID((fBaseID_e)mUnk770) : nullptr;` | 87w / `0x40` | `[29, 30, 31]` | NO (hoists `r29`, 82 diffs) |\n")
md.append("| **Variant Q4 (`if/else` Local Assignment)** | `fBase_c *base = nullptr; if (mUnk770 != 0) base = fManager_c::searchBaseByID((fBaseID_e)mUnk770);` | 86w / `0x30` | `[30, 31]` | NO (separate compare blocks, 51 diffs) |\n")
md.append("| **Variant Q5 (`dActor_c*` Cast)** | `dActor_c *base = (mUnk770 == 0) ? nullptr : (dActor_c*)fManager_c::searchBaseByID((fBaseID_e)mUnk770);` | 88w / `0x40` | `[29, 30, 31]` | NO (hoists `r29`, 80 diffs) |\n")
md.append("| **Variant Q6 (Direct Guarded Delete)** | `if (mUnk770 != 0) { fBase_c *b = fManager_c::searchBaseByID((fBaseID_e)mUnk770); if (b) b->deleteRequest(); }` | 83w / `0x30` | `[30, 31]` | NO (guard-if structure, 48 diffs) |\n\n")

md.append("---\n\n")

md.append("## 4. Work Order Item 2: The Jump Twins (`initializeState_Jump` & `initializeState_BigJump`)\n\n")

md.append("### 4.1. Retail Listing Inspection & Compound-Literal Parameter Audit\n")
md.append("We audited the retail disassembly for both `initializeState_Jump` (`0x800AB9F0`) and `initializeState_BigJump` (`0x800ABD50`):\n")
md.append("- **`initializeState_Jump`** loads from `0x754(r30)` (`mpParamJump`):\n")
md.append("  - True branch (`flag != 0`): `lfs f1, 0x14(r3)` (`mJumpSpeed1.x`), `lfs f0, 0x18(r3)` (`mJumpSpeed1.y`)\n")
md.append("  - False branch (`flag == 0`): `lfs f1, 0x24(r3)` (`mJumpSpeed2.x`), `lfs f0, 0x28(r3)` (`mJumpSpeed2.y`)\n")
md.append("- **`initializeState_BigJump`** loads from `0x754(r30)` (`mpParamJump`):\n")
md.append("  - True branch (`flag != 0`): `lfs f1, 0x1C(r3)` (`mBigJumpSpeed1.x`), `lfs f0, 0x20(r3)` (`mBigJumpSpeed1.y`)\n")
md.append("  - False branch (`flag == 0`): `lfs f1, 0x2C(r3)` (`mBigJumpSpeed2.x`), `lfs f0, 0x30(r3)` (`mBigJumpSpeed2.y`)\n\n")
md.append("**Result**: Retail genuinely reads `mpParamJump` members directly at runtime. There is no pooled anonymous literal for jump speeds.\n\n")

md.append("### 4.2. Observed FP Register Allocation & Instruction Scheduling Mechanism\n")
md.append("In retail:\n")
md.append("```asm\n")
md.append("800ABAC8: mr    r3, r30\n")
md.append("800ABACC: bl    calcJumpRate__18dEnTorideKokoopa_cFv  ; rate -> f1\n")
md.append("800ABAD0: lis   r3, l_EnMuki@ha\n")
md.append("800ABAD4: lbz   r4, 0x348(r30)                       ; mDirection\n")
md.append("800ABAD8: addi  r3, r3, l_EnMuki@l\n")
md.append("800ABADC: lis   r0, 0x4330\n")
md.append("800ABAE0: lbzx  r4, r3, r4                          ; l_EnMuki[mDirection]\n")
md.append("800ABAE4: mr    r3, r30\n")
md.append("800ABAE8: lfs   f0, 0x14(r1)                         ; f0 = speed.y\n")
md.append("800ABAEC: extsb r4, r4\n")
md.append("800ABAF0: stw   r0, 0x18(r1)\n")
md.append("800ABAF4: xoris r0, r4, 0x8000\n")
md.append("800ABAF8: lfd   f4, \"@75355\"@sda21(r0)               ; f4 = 4503601774854144.0 (magic)\n")
md.append("800ABAFC: stw   r0, 0x1c(r1)\n")
md.append("800ABB00: lfs   f2, 0x10(r1)                         ; f2 = speed.x\n")
md.append("800ABB04: lfd   f3, 0x18(r1)                         ; f3 = (0x43300000, 0x8000 ^ muki)\n")
md.append("800ABB08: stfs  f0, 0xec(r30)                        ; mSpeed.y = speed.y (from f0)\n")
md.append("800ABB0C: fsubs f0, f3, f4                           ; f0 = (float)muki\n")
md.append("800ABB10: fmuls f0, f0, f1                           ; f0 = muki * rate\n")
md.append("800ABB14: fmuls f0, f0, f2                           ; f0 = (muki * rate) * speed.x\n")
md.append("800ABB18: stfs  f0, 0xe8(r30)                        ; mSpeed.x = f0\n")
md.append("```\n\n")

md.append("In draft (`k6_sx_late` / 5 diffs):\n")
md.append("```asm\n")
md.append("lfs f0, 0x14(r1)                         ; f0 = speed.y\n")
md.append("lfd f3, \"@27448\"@sda21(r0)               ; f3 = magic (allocated to f3 instead of f4)\n")
md.append("lfs f4, 0x10(r1)                         ; f4 = speed.x (allocated to f4 instead of f2)\n")
md.append("lfd f2, 0x18(r1)                         ; f2 = int-to-float (allocated to f2 instead of f3)\n")
md.append("stfs f0, 0xec(r30)                       ; mSpeed.y = f0\n")
md.append("fsubs f0, f2, f3                         ; f0 = (float)muki\n")
md.append("fmuls f0, f0, f1                         ; f0 = muki * rate\n")
md.append("fmuls f0, f4, f0                         ; f0 = speed.x * (muki * rate) (commuted because f4 > f0)\n")
md.append("stfs f0, 0xe8(r30)\n")
md.append("```\n\n")

md.append("### 4.3. Jump Twins Measured Variants Table\n\n")
md.append("| Variant | `initializeState_Jump` | `initializeState_BigJump` | Observed FP Allocation / Insn Schedule | Analysis / Result |\n")
md.append("| :--- | :---: | :---: | :--- | :--- |\n")
md.append("| **Target (Retail)** | **90w / `0x30` / 0 diff** | **90w / `0x30` / 0 diff** | `f0`=speed.y, `f1`=rate, `f4`=magic, `f2`=speed.x, `f3`=int-pair; `fsubs f0,f3,f4; fmuls f0,f0,f1; fmuls f0,f0,f2` | Exact match on frame, saves, and instruction count. |\n")
md.append("| **Baseline (`k6_sx_late`)** | **90w / `0x30` / 5 diffs** | **90w / `0x30` / 5 diffs** | `f0`=speed.y, `f1`=rate, `f3`=magic, `f4`=speed.x, `f2`=int-pair; `fsubs f0,f2,f3; fmuls f0,f0,f1; fmuls f0,f4,f0` | **Best shape (5 diffs)**. Residual is pure volatile FPR permutation (`f2/f3/f4`). |\n")
md.append("| **Variant V1 (Component-wise x then y)** | 90w / `0x30` / 5 diffs | 90w / `0x30` / 5 diffs | `speed.x = ...; speed.y = ...;` into `mVec2_c speed` | Emits identical loads/stores to struct copy; 5 diffs. |\n")
md.append("| **Variant V2 (Component-wise y then x)** | 90w / `0x30` / 13 diffs | 90w / `0x30` / 13 diffs | `speed.y = ...; speed.x = ...;` | Reverses branch store order into `0x14(r1)` and `0x10(r1)`, regressing to 13 diffs. |\n")
md.append("| **Variant V3 (Separate Scalars `sx, sy`)** | 92w / `0x40` / 80 diffs | 92w / `0x40` / 80 diffs | `float sx, sy;` live across `calcJumpRate()` | Scalars kept live across call force callee-saved FPRs `f30, f31`, growing frame to `0x40` (+2 words). |\n")
md.append("| **Variant V4 (Separate Scalars `sy, sx`)** | 92w / `0x40` / 80 diffs | 92w / `0x40` / 80 diffs | `float sy, sx;` live across `calcJumpRate()` | Same as V3: forces `f30, f31` saves (+2 words, 80 diffs). |\n")
md.append("| **Variant VA (`rate -> sy -> sx -> muki`)** | 90w / `0x30` / 7 diffs | 90w / `0x30` / 7 diffs | `f3`=speed.y, `f4`=speed.x, `f2`=magic, `f0`=int-pair | 7 diffs (speed.y loaded into `f3` instead of `f0`). |\n")
md.append("| **Variant VB (`rate -> sx -> sy -> muki`)** | 90w / `0x30` / 7 diffs | 90w / `0x30` / 7 diffs | `f3`=speed.y, `f4`=speed.x, `f2`=magic, `f0`=int-pair | 7 diffs. |\n")
md.append("| **Variant VC (`rate -> sx -> muki -> sy`)** | 90w / `0x30` / 5 diffs | 90w / `0x30` / 5 diffs | `f0`=speed.y, `f4`=speed.x, `f3`=magic, `f2`=int-pair | Matches `k6_sx_late` at 5 diffs. |\n")
md.append("| **Variant VD (Direct Inline No Locals)** | 90w / `0x30` / 8 diffs | 90w / `0x30` / 8 diffs | `f4`=speed.y, `f0`=speed.x, `f3`=magic, `f2`=int-pair | 8 diffs (unnamed speed.x renumbers to `f0`). |\n")
md.append("| **Variant VE (`speed.x * (muki * rate)`)** | 90w / `0x30` / 6 diffs | 90w / `0x30` / 6 diffs | `f2`=speed.y, `f0`=speed.x, `f4`=magic, `f3`=int-pair | 6 diffs (reverses `f0/f2` for speed.y/speed.x). |\n")
md.append("| **Variants DS1-DS5 (Declaration Splits)** | 90w / `0x30` / 5-7 diffs | 90w / `0x30` / 5-7 diffs | Early declaration splits on volatile `f32 sx, muki;` | Confirming `AGENT_CONTEXT.md:1697`: declaration order does not control volatile FPRs (`f0..f13`). Bottoms out at 5 diffs. |\n\n")

md.append("---\n\n")

md.append("## 5. Work Order Item 3: Fold and Verification (`fndiff.py --all` & `poolcheck.py`)\n\n")

md.append("### 5.1. Fold Confirmation\n")
md.append("- Primary draft `scratch/gemini_round24/d_enemy_toride_kokoopa.cpp` folded with:\n")
md.append("  1. Canonical `nullptr` restored in `setQuakeDead`.\n")
md.append("  2. Anonymous compound literal `(sDeathInfoData){ 0.0f, 3.0f, -4.0f, -0.1875f, &dEnBoss_c::StateID_DieStar, -1, -1, 0, 0xFF }` in `setQuakeDead`.\n")
md.append("  3. File-scope unused `l_die*` declarations removed.\n")
md.append("  4. `initializeState_Jump` and `initializeState_BigJump` folded with the optimal 5-diff shape (`k6_sx_late`).\n")
md.append("- Backup `>> 31` source and compiled object preserved in `scratch/gemini_round24/d_enemy_toride_kokoopa_shift31.cpp` and `.o`.\n\n")

md.append("### 5.2. `poolcheck.py` Output\n")
md.append("```\n")
md.append(poolcheck_out + "\n")
md.append("```\n\n")

md.append("### 5.3. `fndiff.py --all` Full Output\n")
md.append("```\n")
md.append(fndiff_content + "\n")
md.append("```\n\n")

md.append("---\n\n")

md.append("## 6. NOT REACHED\n\n")
md.append("None. All three work order items were investigated, tested across multiple variant suites, verified with retail DOL byte analysis, and folded in full.\n")

with open('GEMINI_RESPONSE.md', 'w', encoding='utf-8') as f:
    f.write(''.join(md))

print('GEMINI_RESPONSE.md successfully generated! Total characters:', len(''.join(md)))
