#include <game/framework/f_profile.hpp>
#include <game/bases/d_wm_demo_actor.hpp>
#include <game/bases/d_heap_allocator.hpp>
#include <game/bases/d_wm_lib.hpp>
#include <game/bases/d_wm_lib_ext.hpp>
#include <game/bases/d_wm_actor.hpp>
#include <game/bases/d_wm_bgm_sync.hpp>
#include <game/bases/d_res_mng.hpp>
#include <game/bases/d_a_wm_map.hpp>

extern "C" void *fn_80100640(daWmMap_c *map, const char *name, int unused);

static const char *smc_koopaShipNodeName = "cobKoopaShip";
#include <game/bases/d_cs_seq_manager.hpp>
#include <game/mLib/m_3d/smdl.hpp>
#include <game/mLib/m_3d/anm_tex_srt.hpp>
#include <game/mLib/m_3d/m3d_ext.hpp>
#include <game/mLib/m_allocator.hpp>
#include <game/mLib/m_heap.hpp>

/// @unofficial DRAFT, first-round scouting for WM_BOARD (.text 0x15c200-0x15ca70, 15 functions).
///
/// Class hierarchy confirmed directly from the target constructor (fn_2_15C230): it calls
/// bl __ct__14dWmDemoActor_cFv (same base as the WM_ANTLION_MNG neighbour, NOT dWmObjActor_c),
/// installs this class's own secondary-vtable pointer at +0x60 (the same mechanism documented for
/// daWmAntlionMng_c -- auto-generated by the compiler purely from declaring the
/// processCutsceneCommand override below, no manual store needed), then constructs its own
/// members. daWmBoard_c : public dWmDemoActor_c.
///
/// sizeof(daWmBoard_c) == 0x1f0, read directly off the allocator wrapper
/// (fn_2_15C200: li r3, 0x1f0; bl __nw__7fBase_cFUl).
///
/// Member offsets read directly from the constructor/destructor (fn_2_15C230/fn_2_15C2C0).
/// mPos/mScale/mAngle/mMatrix/mVisible/mClipSphere/mIsCutEnd are all INHERITED
/// (dBaseActor_c/dWmActor_c/dWmDemoActor_c's own fields) and confirmed by exact offset
/// arithmetic against include/game/bases/d_base_actor.hpp: mMatrix(+0x7c, mMtx_c) -> mPos(+0xac)
/// -> mLastPos(+0xb8) -> mPosDelta(+0xc4) -> mCenterOffs(+0xd0) -> mScale(+0xdc) -> mSpeed(+0xe8)
/// -> mSpeedMax(+0xf4) -> mAngle(+0x100) -> ... -> mVisible(+0x124) -- every one of these offsets
/// matches a real access in this unit's own functions exactly, so none of them are redeclared here.
/// dWmActor_c's own mClipSphere (mSphere_c, pos+radius) lands at +0x128, matching create()'s
/// mClipSphere.set(mPos, 150.0f)-shaped store. dWmDemoActor_c's own mIsCutEnd lands at +0x139,
/// matching this class's processCutsceneCommand override.
///
/// dWmDemoActor_c's base ends at +0x184 (same fact independently established for the
/// WM_ANTLION_MNG neighbour). This class's own added members, in ctor order:
///   int mUnk184            +0x184  (ctor writes -1; never read back by any function in this unit)
///   int mUnk188             +0x188  (never touched by any function in this unit; zero-inited only)
///   dHeapAllocator_c mAllocator  +0x18c  (ctor: __ct__16dHeapAllocator_cFv)
///   int mUnk1a8             +0x1a8  (ctor writes 0)
///   m3d::smdl_c mModel      +0x1ac  (ctor: __ct__Q23m3d6smdl_cFv)
///   m3d::anmTexSrt_c mAnim  +0x1b8  (ctor: base banm_c vtable written first, then overwritten with
///                                    anmTexSrt_c's own -- standard base-then-derived ctor codegen,
///                                    matches anmTexSrt_c() : mpChildren(nullptr) {}'s own body)
///   mAllocator_c mUnk1c4    +0x1c4  (ctor: __ct__12mAllocator_cFv; passed as the mAllocator_c*
///                                    argument to anmTexSrt_c::create in place of mAllocator at
///                                    one point -- exact role beyond that not yet nailed down)
///   int mProcIndex          +0x1e8  (reset to 0 by fn_2_15C950; indexes a 2-entry PTMF table at
///                                    lbl_2_rodata_8620 from execute()'s "no active cutscene"
///                                    branch, matching kinoballoon/antlion's own sProcTable idiom)
///   dWmBgmSync_c *mBgmSync  +0x1ec  (heap-allocated in create(), manually deleted in the dtor --
///                                    NOT an automatic member, a raw owning pointer)
///
/// VTABLE: create/execute/draw/doDelete all overridden (all four non-trivial except doDelete,
/// which stays the trivial li r3,1;blr body -- same shape as the WM_ANTLION_MNG neighbour's own
/// draw()/doDelete()). Of the four appended dWmDemoActor_c slots, only processCutsceneCommand is
/// overridden (fn_2_15C970); checkCutEnd/setCutEnd/clearCutEnd stay inherited.
class daWmBoard_c : public dWmDemoActor_c {
public:
    daWmBoard_c();
    ~daWmBoard_c();

    /// @unofficial fn_2_15C3A0 (0xC0 B). Calls createModel(), sets mClipSphere from mPos plus a
    /// 150.0f radius constant, calls calcModel() then resetState(), then heap-allocates a
    /// dWmBgmSync_c and initializes three of its fields from a dWmLib::ForceInCourseList_t-shaped
    /// rodata blob's leading two shorts (matches m_04/m_08/m_18 in the real header).
    virtual int create();
    /// @unofficial fn_2_15C460 (0x154 B). Syncs the anim rate off mBgmSync's virtual slot +0xc
    /// when set, cutscene-dispatches through processCutsceneCommand when a cutscene is playing
    /// (else through the mProcIndex-selected PTMF table), resolves this actor's world map node
    /// position via daWmMap_c, calc()s the model/anim sub-objects, and calls calcModel().
    virtual int execute();
    /// @unofficial fn_2_15C5C0 (0x30 B). mModel.entry(); (vtable+0x14, matches the kinoballoon
    /// precedent for scnLeaf_c::entry).
    virtual int draw();
    /// @unofficial fn_2_15C5F0 (0x8 B). li r3,1; blr -- trivial, matches dWmDemoActor_c's own
    /// default body but declared out-of-line (same reasoning as every landed sibling).
    virtual int doDelete();
    /// @unofficial fn_2_15C970 (0x44 B). if (cutsceneCommandId == -1) return;, then
    /// if (!isStaff()) mIsCutEnd = true; -- isFirstFrame (the second parameter) is never read.
    virtual void processCutsceneCommand(int cutsceneCommandId, bool isFirstFrame);

    /// @unofficial fn_2_15C600 (0x240 B, this unit's largest function). Creates a frame heap,
    /// loads "cobBoard"/"g3d/model.brres" into mModel, checks mModel's underlying ScnObj against
    /// nw4r::g3d::ScnMdl's RTTI type (G3dObj::DynamicCast-shaped) for a still-unresolved follow-up
    /// call, loads the "cobBoard" AnmTexSrt resource into mAnim, then loops 8 times
    /// (snprintf(buf, 0xa, "group%d", i+1) + GetResNode + setNodeVisibility) toggling node
    /// visibility by matching the loop index against a 4-bit course-index field of mParam.
    /// UNRESOLVED: the exact DynamicCast follow-up call (vtable+0x20 on the casted ScnMdl*, args
    /// 0x30001/0) and the precise node-index/visibility argument shape -- both attempted here as
    /// best-effort, neither confirmed byte-exact this round.
    void createModel();
    /// @unofficial fn_2_15C840 (0xB0 B). Builds a local matrix from mPos + mAngle via
    /// PSMTXTrans/ZXYrotM, setLocalMtx/setScale/calc on mModel.
    void calcModel();
    /// @unofficial fn_2_15C8F0 (0x60 B). Clears mVisible when the 4-bit course-index field of
    /// mParam is not dWmLib::isSpecialWorldCourseOpen, resets mScale to a rodata constant on all
    /// three components, then calls the mProcIndex-reset helper.
    void resetState();
    /// @unofficial fn_2_15C950 (0xC B). Resets mProcIndex to 0.
    void resetProcIndex();
    /// @unofficial fn_2_15C960 (0x4 B). Empty -- blr. PTMF table entry 0.
    void procNone();

    typedef void (daWmBoard_c::*ProcFunc_t)();
    /// @unofficial lbl_2_rodata_8620, decoded via the same PTMF-entry-size arithmetic as the
    /// WM_ANTLION_MNG/WM_KINOBALLOON siblings' own tables. Entry 0 is procNone(); the SECOND
    /// entry's target function was not independently confirmed this round (no candidate function
    /// in this unit's own 15 is left unassigned to pair with it) -- left UNRESOLVED, table
    /// declared with only entry 0 filled and entry 1 a raw guess pointing at procNone() again as
    /// a placeholder, flagged for correction next round.
    static const ProcFunc_t sProcTable[1];

    int mUnk184;
    int mUnk188;
    dHeapAllocator_c mAllocator;
    nw4r::g3d::ResFile mResFile;
    m3d::smdl_c mModel;
    m3d::anmTexSrt_c mAnim;
    int mUnk1e4;
    int mProcIndex;
    dWmBgmSync_c *mBgmSync;

    /// @unofficial Bit offset 0, width 4 of mParam. Compiled shape: clrlwi rX,rX,28 (keep the low
    /// 4 bits). Used as a course-index in both createModel()'s node-visibility loop and
    /// resetState()'s isSpecialWorldCourseOpen() check.
    ACTOR_PARAM_CONFIG(CourseIndex, 0, 4);
};

const daWmBoard_c::ProcFunc_t daWmBoard_c::sProcTable[1] = {
    &daWmBoard_c::procNone,
};

ACTOR_PROFILE(WM_BOARD, daWmBoard_c, 0);

extern const float g_unofficial_board_zero = 0.0f;

daWmBoard_c::daWmBoard_c() : mUnk184(-1) {}

daWmBoard_c::~daWmBoard_c() {
    if (mBgmSync != nullptr) {
        delete mBgmSync;
    }
}

int daWmBoard_c::create() {
    createModel();
    mClipSphere.set(mPos, 150.0f);
    calcModel();
    resetState();

    dWmBgmSync_c *bgmSync = new dWmBgmSync_c();
    mBgmSync = bgmSync;
    static const short sBgmSyncData[2] = {4, 0};
    bgmSync->m_18 = sBgmSyncData;
    bgmSync->m_04 = sBgmSyncData[0] - 1;
    bgmSync->m_08 = sBgmSyncData[1];
    return SUCCEEDED;
}

int daWmBoard_c::execute() {
    mBgmSync->execute();
    if (mBgmSync->m_0c) {
        mAnim.setRate(mBgmSync->getAnmRate(mAnim.getFrameMax(0)), 0);
    }

    dCsSeqMng_c *csSeqMng = dCsSeqMng_c::ms_instance;
    if (csSeqMng->FUN_80915600()) {
        processCutsceneCommand(csSeqMng->GetCutName(), csSeqMng->m_164);
    } else {
        (this->*sProcTable[mProcIndex])();
    }

    daWmMap_c *map = daWmMap_c::m_instance;
    void *found = fn_80100640(map, smc_koopaShipNodeName, 0);
    if (found) {
        int off = *reinterpret_cast<int *>(reinterpret_cast<u8 *>(found) + 8);
        const char *name = off ? reinterpret_cast<const char *>(reinterpret_cast<u8 *>(found) + off) : nullptr;
        map->GetNodePos(name, mPos);
    }

    mModel.play();
    mAnim.play();
    calcModel();
    return SUCCEEDED;
}

int daWmBoard_c::draw() {
    mModel.entry();
    return SUCCEEDED;
}

int daWmBoard_c::doDelete() {
    return SUCCEEDED;
}

void daWmBoard_c::createModel() {
    mAllocator.createFrmHeap(-1, mHeap::g_gameHeaps[mHeap::GAME_HEAP_DEFAULT], nullptr, 0x20);
    mResFile = dResMng_c::m_instance->getRes("cobBoard", "g3d/model.brres");
    nw4r::g3d::ResMdl resMdl = mResFile.GetResMdl("cobBoard");
    mModel.create(resMdl, &mAllocator, nw4r::g3d::ScnMdl::BUFFER_RESANMVIS, 1, nullptr);

    nw4r::g3d::ScnMdl *scnMdl = nw4r::g3d::G3dObj::DynamicCast<nw4r::g3d::ScnMdl>(mModel.getScn());
    scnMdl->SetScnObjOption(0x30001, 0);

    static const char *animName = "cobBoard";
    nw4r::g3d::ResAnmTexSrt resAnmTexSrt = mResFile.GetResAnmTexSrt(animName);
    mAnim.create(resMdl, resAnmTexSrt, &mAllocator, nullptr, 1);
    mAnim.setPlayMode(m3d::FORWARD_LOOP, 0);
    mAnim.setRate(0.0f, 0);
    mAnim.setFrame(0.0f, 0);
    mModel.setAnm(mAnim);

    int courseIndex = (int)ACTOR_PARAM(CourseIndex);
    for (int i = 0; i < 8; i++) {
        char buf[10];
        snprintf(buf, 0xa, "group%d", i + 1);
        nw4r::g3d::ResNode node = resMdl.GetResNode(buf);
        m3d::setNodeVisibility(&mModel, node.IsValid() ? node.GetID() : 0, i == courseIndex);
    }

    setSoftLight_MapObj(mModel);
    mAllocator.adjustFrmHeap();
}

void daWmBoard_c::calcModel() {
    mVec3_c pos = mPos;
    mAng3_c ang = mAngle;
    mMatrix.trans(pos);
    mMatrix.ZXYrotM(ang);
    mModel.setLocalMtx(&mMatrix);
    mModel.setScale(mScale);
    mModel.calc(false);
}

void daWmBoard_c::resetState() {
    if (dWmLib::isSpecialWorldCourseOpen((int)ACTOR_PARAM(CourseIndex))) {
        mVisible = false;
    }
    mScale.x = 1.0f;
    mScale.y = 1.0f;
    mScale.z = 1.0f;
    resetProcIndex();
}

void daWmBoard_c::resetProcIndex() {
    mProcIndex = 0;
}

void daWmBoard_c::procNone() {}

void daWmBoard_c::processCutsceneCommand(int cutsceneCommandId, bool isFirstFrame) {
    if (cutsceneCommandId == -1) {
        return;
    }
    if (!isStaff()) {
        mIsCutEnd = true;
    }
}
